apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: bookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: frontend-appapp
    spec:
      containers:
      - name: frontend-container
        image: kartikmehta/book-Frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
